### PR TITLE
Give header files a uniform indentation

### PR DESCRIPTION
**Pull request by htibosch**
Description
-----------
In this PR I looked at all 'extern "C"' statements in the header files. I want to make sure that they're all written in a uniform way, and that the closing bracket gets a comment. I didn't like these minimal statements that allow an extra indentation by Uncrustify:

~~~diff
-#ifdef __cplusplus
-    extern "C" {
-#endif
-
-/* functions */
-
-#ifdef __cplusplus
-}
-#endif
~~~

I like to replace it with these:

~~~diff
+/* *INDENT-OFF* */
+#ifdef __cplusplus
+    extern "C" {
+#endif
+/* *INDENT-ON* */
+
+/* functions */
+
+/* *INDENT-OFF* */
+#ifdef __cplusplus
+    } /* extern "C" */
+#endif
+/* *INDENT-ON* */
~~~
as they're used in most situations already.

Another reason for the above change is that the Windows' Uncrustify-0.69.0 has a problem with several header files.  Within Windows, I **can not** get the same result as with Uncrustify 0.69.0_f on Linux. Window's Uncrustify proposes this change:

~~~diff
-    #ifdef __cplusplus
-        } /* extern "C" */
-    #endif
+    #ifdef __cplusplus
+}            /* extern "C" */
+    #endif
~~~
which looks strange.

Also I repaired some copy/paste errors at the end of header files, for instance in FreeRTOS_IPv4.h :

~~~diff
-#endif /* FREERTOS_IP_H */
+#endif /* FREERTOS_IPV4_H */
~~~

There are about 7 of such mistypes.

And also I changed these:

~~~
-#endif /* ifndef FREERTOS_DNS_PARSER_H */
+#endif /* FREERTOS_DNS_PARSER_H */
~~~

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by moninom1 — APPROVED** [review]

**Review by ActoryOu — DISMISSED** [review]
It looks good to me.

**Review by ActoryOu — APPROVED** [review]

**Review by AniruddhaKanhere — APPROVED** [review]
Thank you @htibosch for this PR.

**Pull request merged**
