### PR TITLE
BufferAllocation_2: respect 0 length buffer request

### PR DESCRIPTION
**Pull request by twpedersen**
The pxGetNetworkBufferWithDescriptor() documentation states:

	If xRequestedSizeBytes is zero then the returned network
	buffer descriptor will not reference an Ethernet buffer
	(the reference is set to NULL).

But this did not match the implementation. 2 bytes were
unconditionally being added to the requested size, and the
returned NetworkBufferDescriptor_t would have a nonzero
pucEthernetBuffer.

Move the code performing length alignment as is into the
branch checking whether size is nonzero. This lets the
caller request a bare NetworkBufferDescriptor_t to eg.
implement zero copy RX.

### CODE REVIEW

**Comment by twpedersen** [comment]
`FAIL: ./portable/BufferManagement/BufferAllocation_2.c (File size changed from 15804 to 15986)` ?

**Comment by yourslab** [comment]
Hi @twpedersen. Please use uncrustify to format `BufferAllocation_2.c` with the following config: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/tools/uncrustify.cfg

**Comment by twpedersen** [comment]
thanks @yourslab. I ran `BufferAllocation_2.c` through uncrustify and repushed.

**Comment by twpedersen** [comment]
Thanks @htibosch. Good catch. I think it might be better to initialize `xDataLength` along with `pucEthernetBuffer` while freeing the descriptor in`vReleaseNetworkBufferAndDescriptor()`?

**Comment by htibosch** [comment]
> I think it might be better to initialize `xDataLength` along with `pucEthernetBuffer` while freeing the descriptor in`vReleaseNetworkBufferAndDescriptor()`?

Do you mean the following location?
~~~c
 void vReleaseNetworkBufferAndDescriptor( NetworkBufferDescriptor_t * const pxNetworkBuffer )
 {
     BaseType_t xListItemAlreadyInFreeList;

     /* Ensure the buffer is returned to the list of free buffers before the
     * counting semaphore is 'given' to say a buffer is available.  Release the
     * storage allocated to the buffer payload.  THIS FILE SHOULD NOT BE USED
     * IF THE PROJECT INCLUDES A MEMORY ALLOCATOR THAT WILL FRAGMENT THE HEAP
     * MEMORY.  For example, heap_2 must not be used, heap_4 can be used. */
     vReleaseNetworkBuffer( pxNetworkBuffer->pucEthernetBuffer );
     pxNetworkBuffer->pucEthernetBuffer = NULL;
+    pxNetworkBuffer->xDataLength = 0U;

     taskENTER_CRITICAL();
~~~
I also think that is semantically more correct, `pucEthernetBuffer` and `xDataLength` are kept together.

**Comment by twpedersen** [comment]
Exactly. I updated the PR with that change.

**Review by n9wxu — APPROVED** [review]

**Pull request merged**
