### PR TITLE
Update Portable Folder for End Point changes

### PR DESCRIPTION
**Pull request by kar-rahul-aws**
Added changes in WinPCap Port for IPV4 Endpoint changes

Network Interface changes for WinPCap Port 

Description
-----------
Added Endpoint changes and Network Interface structure changes

Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by htibosch — COMMENTED** [review]
Thank you for this PR. I will check it later in a real project.
Please make the change suggested below.

**Comment by htibosch** [comment]
At this moment, `xNetworkInterfaceOutput()` is still called directly (in the "/single" mode).

Eventually this function will also be coupled to an interface:

    pxInterface->pfInitialise = xNetworkInterfaceInitialise;
    pxInterface->pfOutput = xNetworkInterfaceOutput;
    pxInterface->pfGetPhyLinkStatus = xGetPhyLinkStatus;

and the code will call `pxInterface->pfOutput()` in stead.

That is also why the above functions must be declared `static`, so that multiple interfaces can be used without a conflict.

**Review by moninom1 — APPROVED** [review]

**Review by moninom1 — COMMENTED** [review]
/bot run uncrustify

**Pull request merged**
