### PR TITLE
Merge buffer allocation methods

### PR DESCRIPTION
**Pull request by holden-zenith**
Merge Buffer Allocations methods

Description
-----------
The two files had fallen out of sync but can share a significant amount of code. A config macro should be defined to determine which method to use.

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
Thank you @holden-zenith for this welcome initiative.

`BufferAllocation_1.c` indeed has much more safety checks. That is the module that is mostly used.

Two problems can emerge:

- A leak of buffers: they get allocated but not freed.
- Buffers get released twice.

In my private copy I have even added two hidden fields: the places where a buffer was allocated, and where it was released. I don't think that this is useful as a general feature.

Functions like `bIsValidNetworkDescriptor()` are very useful and it would be nice if such functions are available in both files.

Please ping me if you want to have the changes tested.

**Comment by holden-zenith** [comment]
@htibosch if you would like to test it that would be great. I've run them both on my STM32F7 so far. If you have any suggestions or changes let me know.

**Comment by amazonKamath** [comment]
> @htibosch if you would like to test it that would be great. I've run them both on my STM32F7 so far. If you have any suggestions or changes let me know.

**Comment by amazonKamath** [comment]
@holden-zenith we will review your PR next week and provide further feedback. Apologies for the delay, we are in the middle of pushing a release candidate on [FreeRTOS:dev/IPv6_integration](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/dev/IPv6_integration)

**Pull request closed without merging**
