### PR TITLE
Eliminate some warnings

### PR DESCRIPTION
**Pull request by pete-pjb**
# Eliminate some warnings  

Description
-----------

Eliminate some printf() related warning messages by changing specifiers and applying appropriate casts.  

Test Steps
-----------
Build the source code with GCC Xilinx ARM compiler version 11.2 to generate said warnings.  

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aggarg — APPROVED** [review]

**Review by kstribrnAmzn — DISMISSED** [review]

**Comment by kstribrnAmzn** [comment]
Let me see what I can do Pete. The errors aren't always obvious.

**Comment by kstribrnAmzn** [comment]
Looks like the formatting check was broken. The other check failure was just transient. I've pinged @aggarg once again to approve.

**Review by aggarg — APPROVED** [review]

**Comment by pete-pjb** [comment]
Hi @kstribrnAmzn ,

I see, guessing by your commit it was a formatting problem...  I work in Windows and don't have any experience of Uncrustify, I have now added it  to my mingw folders and will see if I can get it working so I can run it before I submit any future pull requests.

Thanks for for looking into it.

Kind Regards,

Pete

**Pull request merged**
