### PR TITLE
Fixes the TCP zero-copy functionality...

### PR DESCRIPTION
**Pull request by evpopov**
As discussed in #1008 
It appears that this worked at some point but then got broken.
To reproduce: call FreeRTOS_send() with pvBuffer being NULL and the call always fails.

### CODE REVIEW

**Comment by bjsowa** [comment]
Is the TCP zero-copy functionality documented anywhere? Are there any examples I can find?

**Comment by evpopov** [comment]
@bjsowa 
Check these forum posts
[https://forums.freertos.org/t/releaseudppayloadbuffer-but-for-tcp/13890](https://forums.freertos.org/t/releaseudppayloadbuffer-but-for-tcp/13890) That post also has a link to the FTP code that you can also look at.
[https://forums.freertos.org/t/stm32h743-freertos-tcp-issue-with-zero-copy/15390](https://forums.freertos.org/t/stm32h743-freertos-tcp-issue-with-zero-copy/15390) This post has a bunch of gems but you may have to read through to the end.

**Comment by shubnil** [comment]
Hi @evpopov , We have a new fix https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/1023 in the zero copy flow. Please rebase the PR on top of the same. After that we would be good to merge.

**Comment by evpopov** [comment]
@shubnil Thanks for letting me know.

**Comment by evpopov** [comment]
@shubnil , that unit test that is failing because my PR allows FreeRTOS_send to be called with a NULL pointer and the unit test expects a call with a NULL pointer to fail, but it now succeeds.
The unit test should be modified, but I do not feel comfortable modifying it. Can someone with more experience help with this and disable that specific check in the unit test?

Thanks.

**Review by moninom1 — APPROVED** [review]

**Comment by shubnil** [comment]
Hi @evpopov,

We understand the situation. We have fixed the unit test failure for this PR.
However, it will be good for long term if you can create a Linux machine setup or install a virtual Linux machine on your windows. We can help you in creating the local unit test setup.

Thanks,
Shub

**Review by shubnil — APPROVED** [review]

**Pull request merged**
