### PR TITLE
IPv4/single: resubmit ARP cache changes found in PR #366

### PR DESCRIPTION
**Pull request by htibosch**
Description
-----------
In December 2021, after protocol testing, @AniruddhaKanhere submitted some changes regarding the usage of the ARP cache, which he documented as follows:

"This PR removes the call to refresh ARP cache entry when a UDP/TCP packet is received. It replaces that call with a function to only update the ARP entry age.
Additionally, the translation of IP->MAC must be done through ARP cache. Thus this PR translates an IP to MAC using ARP cache instead of switching the source and destination MAC address before sending any packet"

In today's main branch, some of the changes have disappeared. I assume that this happened accidentally.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AniruddhaKanhere** [comment]
Thank you @htibosch for this PR. I am also not sure why the changes disappear.
Regardless, grateful if you could fix the unit-tests.

**Comment by shubnil** [comment]
Hi Hein, Do we still this need this change. If yes, please help in fixing the unit-test and it will be good if we can create a PR for dev/ipv6_integration branch.

**Comment by htibosch** [comment]
@shubnil wrote:
> Hi Hein, Do we still this need this change. If we do, please help in fixing the unit tests and it will be good if we can create a PR for dev/ipv6_integration branch.

Yes we still need it, both in IPv4 and dev/IPv6_integration.

**Review by sirnish — APPROVED** [review]

**Review by shubnil — APPROVED** [review]

**Pull request merged**
