### PR TITLE
TM4C: Enable PHY interrupts for link changes

### PR DESCRIPTION
**Pull request by martinaao**
Enable PHY interrupts for link changesEnable PHY interrupts for link changes

Description
-----------
The EMAC must be reconfigured after PHY link changes. In the current NetworkInterface.c code this is done in the PHY interrupt handler, however the interrupts for the internal PHY are not enabled, so the MAC is never reconfigured after initial link-up.

This results in unstable startup of the EMAC. 

See the documentation in Tivaware for EMACPHYConfigSet.

@jscott-hotstart Thanks a lot for adding support for this board

Test Steps
-----------
This issue is hard to reproduce since it triggers undefined behaviour in the EMAC. It seems to be very timing sensitive. When failing the symptomes are missing interrupts from the EMAC.

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
Thank you @martinaao for this PR.

Unfortunately, I still don't have a TM4C evaluation board to test the changes.

Were you able to test the change in a real application?

I understand that your allows interrupts triggered by a Link Status change. What happens if the LS goes down? Is there a speed and duplex when a PHY is not connected?

**Comment by martinaao** [comment]
> Were you able to test the change in a real application?

Yes, i have tested on a real world application but only on the Eval Board EK-TM4C1294XL for now. In our application every 4-5 builds (with code changes) would fail until i made this change.

> 
> I understand that your allows interrupts triggered by a Link Status change. What happens if the LS goes down? Is there a speed and duplex when a PHY is not connected?
I have not seen problems after taking link down and up again, when the LS goes down the MAC is not re-configured. 

According to the documentation from TI the PHY must be configured first, then the EMAC since the MAC parameters are latched by the HW after the peripheral is reset. Since the configuration of the PHY can be reset in phyHandling.c we must wait for the speed change interrupt (that always comes after reset) before re-configuring the EMAC.

**Review by htibosch — APPROVED** [review]
Unfortunately I do not have the hardware, but I trust on your reports about testing in real hardware.
I approve this PR.
Thanks a lot, Hein

**Review by paulbartell — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Comment by AniruddhaKanhere** [comment]
@martinaao apologies but can you please rebase your branch?
The `portable/NetworkInterface/TM4C/NetworkInterface.c` file is now moved one level deep in source folder like so 'source/portable/NetworkInterface/TM4C/NetworkInterface.c`

**Comment by AniruddhaKanhere** [comment]
Another option is that I can create a PR on your behalf. Would you like me to do that?

**Comment by AniruddhaKanhere** [comment]
I have rebased and recreated this PR here: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/478.

Closing this PR now. Thank you @martinaao.

**Pull request closed without merging**
