### PR TITLE
Update sockets header to include ntop/pton IPv4/v6 API declarations

### PR DESCRIPTION
**Pull request by tony-josi-aws**
Description
-----------
This PR updates the sockets header file with declarations for ntop/pton IPv4/v6 API declarations.

Test Steps
-----------
Build combination checks

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- ~[ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.~

Related Issue
-----------

Implicit declaration warnings if `FreeRTOS_IPv4_Sockets.h` is not included specificaly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by moninom1 — APPROVED** [review]

**Comment by htibosch** [comment]
Won't there be more declarations that we need from FreeRTOS_IPv4_Sockets.h and FreeRTOS_IPv6_Sockets.h ?
This PR you only moves the declaration of pton/ntop to FreeRTOS_Sockets.h

And also, your solution is confusing. A functions' header is found in FreeRTOS_IPv4_Sockets.h, while its definition is found in FreeRTOS_Sockets.c

**Comment by tony-josi-aws** [comment]
@htibosch 

> Won't there be more declarations that we need from FreeRTOS_IPv4_Sockets.h and FreeRTOS_IPv6_Sockets.h ?
> This PR you only moves the declaration of pton/ntop to FreeRTOS_Sockets.h

Other than pton/ntop functions all other functions declared in the FreeRTOS_IPv4_Sockets.h and FreeRTOS_IPv6_Sockets.h are for internal use for stack. Some of these functions require the definition of `FreeRTOS_Socket_t` (`xSOCKET`) which is defined in the FreeRTOS_IP_Private.h.

> And also, your solution is confusing. A functions' header is found in FreeRTOS_IPv4_Sockets.h, while its definition is found in FreeRTOS_Sockets.c

In that case we could consider moving pton/ntop functions to `FreeRTOS_Sockets.c`.

**Comment by htibosch** [comment]
Ok, that's a very good reason to keep them local to the library. Thanks

**Review by shubnil — APPROVED** [review]

**Pull request merged**
