### PR TITLE
WIP - Separate out sockets

### PR DESCRIPTION
**Pull request by holden-zenith**
Separate out sockets, if the idea is approved then I will finish this PR and fix any affected unit tests.

Description
-----------
The sockets file has become the most cumbersome file, this separates TCP/UDP sockets and also better isolates socket code from other files. None of the API or logic is altered, this is mostly just copy pasta.

Test Steps
-----------
Not finished. Getting feedback first.

Related Issue
-----------
Size of FreeRTOS_Sockets.c file.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by holden-zenith** [comment]
@AniruddhaKanhere @htibosch Is there any point in finishing this or is it a waste of effort?

**Comment by shubnil** [comment]
Hi @holden-zenith , Thanks for the PR, We are discussing this internally and will get back to you soon. Thanks for being patient.

**Comment by holden-zenith** [comment]
@shubnil no problem. I can redo with much more concise and reviewable commits or if you have any other ideas on something to help out with let me know, I was just messing around with it to see if it was worth it for now.

**Comment by shubnil** [comment]
@holden-zenith This is an interesting proposal and we are always open to improvement suggestions. I agree with you partially. I agree to the point that socket file needs some cleaning, However, I do not completely agree with the point that UDP and TCP sockets needs to be differentiated as socket layer being based on BSD sockets need not be different based on the underlying protocol. It will be great if you can create a PR just to clean up the socket file.

**Comment by holden-zenith** [comment]
@shubnil What did you have in mind for doing that? Also, the intention wasn't really to differentiate but to ease the use of all the #if (ipconfigUSE_TCP) and it basically splits the file size in a 1-3 ratio by separating tcp/udp, but I understand your point.

**Comment by holden-zenith** [comment]
@shubnil related to what I was working on? Or keeping everything in sockets.h and cleaning it up as you mentioned?

**Pull request closed without merging**
