### PR TITLE
Disable counter interrupts in the STM32Fxx driver

### PR DESCRIPTION
**Pull request by holden-zenith**
Related to the [STM32H7](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/346) version

### CODE REVIEW

**Review by htibosch — APPROVED** [review]
Thank you @holden-zenith for proposing this change. I won't hurt to disable counter interrupts.

One question out of curiosity: why didn't anybody complain about these counters. I remember that their interrupts will keep triggering until you read the specific counter.

I did see the problem in an STM32H board, and I disabled all MMC counter interrupts in [HAL_ETH_Init](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/source/portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.c#L438).

Maybe you want to move your patch from NetworkInterface.c to `HAL_ETH_Init()` in stm32fxx_hal_eth.c so we keep them as similar as possible :-) ?

**Comment by holden-zenith** [comment]
@htibosch I took it from [here](https://community.st.com/s/question/0D50X0000AIdSc0SQF/unwanted-interrupts-for-ethernetmac-mmc). Also, it is in HAL_ETH_Init

**Comment by amazonKamath** [comment]
@holden-zenith  - I synced your branch to tip of the [FreeRTOS:dev/IPv6_integration](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/dev/IPv6_integration).    It would be great if you can confirm if https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/773 was because your branch being out of sync ?

**Comment by holden-zenith** [comment]
@amazonKamath No, the issue is still there, at least for me. Although I haven't put much time into investigating.

**Review by paulbartell — APPROVED** [review]

**Review by paulbartell — APPROVED** [review]

**Review by amazonKamath — APPROVED** [review]

**Pull request merged**
