### PR TITLE
Fixes the build issue with unit tests for IP timers 

### PR DESCRIPTION
**Pull request by tony-josi-aws**
Description
-----------
This PR fixes the build issues for the unit tests for IP timers as part of the integration process of IPv4/IPv6.

Test Steps
-----------

```
cmake -S test/unit-test -B test/unit-test/build/
make -C test/unit-test/build/ all
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by htibosch — COMMENTED** [review]
At this moment, `xNetworkInterfaceOutput()` is still called directly (in the "/single" mode).
...
**EDIT** : the comment here was meant to be placed [here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/603#pullrequestreview-1212923551) at PR #602.

**Comment by moninom1** [comment]
Please update the commit message

**Pull request merged**
