### PR TITLE
No searching for end-points when responding to mDNS/LLMNR/NBNS

### PR DESCRIPTION
**Pull request by evpopov**
Description
-----------
When name queries (mDNS/LLMNR/NBNS) need to be responded to, the current code searches for an end-point to use when sending the response. This PR gets rid of this search and uses the end-point on which the original request was received. This removes the possibility of a malformed request causing responses to be sent on other interfaces.
A lot more details can be found in  #1042

I am not sure if any test are being affected by this change.
I have also removed ```prvFindEndPointOnNetMask( NetworkBufferDescriptor_t * pxNetworkBuffer )``` since it is no longer used. I also believe the whole premise of having a function that searches for and end-point to be used for a response is incorrect. Any response should be using the end-point of the original request, but this is just my opinion. Please let me know what you think and if you believe I should keep this function in the codebase even though it is no longer used.

Related Issue
-----------
 #1042

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by n9wxu — APPROVED** [review]

**Review by ActoryOu — APPROVED** [review]

**Comment by n9wxu** [comment]
Please take a look at the PR checks above and correct the issues.

**Comment by htibosch** [comment]
@n9wxu wrote:

> Please take a look at the PR checks and correct the issues.

To @evpopov, adapted unit tests: [FreeRTOS_DNS_Parser_utest.zip](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/files/13749122/FreeRTOS_DNS_Parser_utest.zip)

**Comment by evpopov** [comment]
Thanks @htibosch !
I really appreciate you jumping in and helping with the updated unit test

**Comment by htibosch** [comment]
I saw that the coverage was still no 100% and repaired that in these source files:

[changes_coverage.zip](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/files/13871118/changes_coverage.zip)

source\FreeRTOS_DNS_Parser.c
test\unit-test\FreeRTOS_DNS_Parser\FreeRTOS_DNS_Parser_utest.c

I had forgotten the new [`configASSERT()`](https://github.com/evpopov/FreeRTOS-Plus-TCP/blob/788ec566e3bf16bdb1ebb84349b851272b1a1b22/source/FreeRTOS_DNS_Parser.c#L876).

I could also make this simplification:
~~~diff
-    pxIPHeader->ulSourceIPAddress = ( pxEndPoint != NULL ) ? pxEndPoint->ipv4_settings.ulIPAddress : 0U;
+    pxIPHeader->ulSourceIPAddress = pxEndPoint->ipv4_settings.ulIPAddress;
~~~
because `pxEndPoint` is proven to be not NULL.

**Review by tony-josi-aws — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
