### PR TITLE
Speed up unit tests

### PR DESCRIPTION
**Pull request by HTRamsey**
Speed up unit tests

Description
-----------
I'm not aware of any reason not to do this, but otherwise unit tests can take forever.

Test Steps
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
@HTRamsey wrote:
> otherwise unit tests can take forever.

Do you mean that it takes a long time, or does it get into an endless loop?

On my virtual Ubuntu, compiling UT takes ages:
~~~
    real      34m46.745s
    user      8m55.193s
    sys       6m15.857s
~~~

I also tried your proposed changes, but it still takes the same long time. Do I miss anything?

Thanks

**Comment by HTRamsey** [comment]
@htibosch  [Here](https://github.com/HTRamsey/FreeRTOS-Plus-TCP/actions/runs/7770042974/job/21189743927) is an example of a standard build time (4m 12s) and [Here](https://github.com/HTRamsey/FreeRTOS-Plus-TCP/actions/runs/7770052600/job/21189764344) is the quicker build (1m 33s)

**Comment by htibosch** [comment]
> @htibosch [Here](https://github.com/HTRamsey/FreeRTOS-Plus-TCP/actions/runs/7770042974/job/21189743927) is an example of a standard build time (4m 12s) and [Here](https://github.com/HTRamsey/FreeRTOS-Plus-TCP/actions/runs/7770052600/job/21189764344) is the quicker build (1m 33s)

These [UT checks](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/actions/runs/7760773333/job/21167760155?pr=1084) were done before the change:

image

so I am not yet impressed.

**Comment by HTRamsey** [comment]
@htibosch I'm not sure I follow. It's 3-4x quicker when using Ninja, that's pretty good.

**Comment by tony-josi-aws** [comment]
@HTRamsey, thanks for the PR.

It improves the UT build time by a good margin (the total build time was around ~1 minute when tested locally).

@htibosch The results you get might be because the build is done on a virtual machine, and parallel builds might be limited by the number of cores you have assigned to the virtual machine.

**Review by tony-josi-aws — APPROVED** [review]

**Review by moninom1 — APPROVED** [review]

**Pull request merged**
