### PR TITLE
IPv4/single: added comments to FreeRTOSIPConfigDefaults.h

### PR DESCRIPTION
**Pull request by htibosch**
Description
-----------
Added many inline comments to the header file 'FreeRTOSIPConfigDefaults.h'

More complete documentation can be found on [freertos.org](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/TCP_IP_Configuration.html), which will be updated soon.

I left the definitions exactly as they were, not changing any value. I did reorder some items, to keep similar macros together as a group: ARP, ICMP, DHCP, DNS etc.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AniruddhaKanhere** [comment]
Hello Hein,

Thank you for this PR. I see that the kernel submodule pointer has also been updated in this. I don't think that was intended - was it?
Can you take a look and please remove the changes to the kernel submodule pointer?

Thanks

**Comment by htibosch** [comment]
Thank you Aniruddha for your comments, I applied all suggestions. Although I still have doubts about:
~~~c
/* This file should be included only after the configuration files FreeRTOSConfig.h and
 * FreeRTOSIPConfig.h have been included already.
~~~
When the comment says **should**, the user might think that action is required. I thought more of a confirmation:
~~~c
/* This file is included after the configuration files FreeRTOSConfig.h and
 * FreeRTOSIPConfig.h have been included already.
~~~
What do you think?

**Comment by AniruddhaKanhere** [comment]
> Thank you Aniruddha for your comments, I applied all suggestions. Although I still have doubts about:
> 
> ```c
> /* This file should be included only after the configuration files FreeRTOSConfig.h and
>  * FreeRTOSIPConfig.h have been included already.
> ```
> 
> When the comment says **should**, the user might think that action is required. I thought more of a confirmation:
> 
> ```c
> /* This file is included after the configuration files FreeRTOSConfig.h and
>  * FreeRTOSIPConfig.h have been included already.
> ```
> 
> What do you think?

Maybe it should say "must"? That is: `This file must be included ...`

**Comment by htibosch** [comment]
About the commit "A minor change: should becomes must": that was the last thing open. Thanks for reviewing.

**Review by AniruddhaKanhere — APPROVED** [review]

**Review by n9wxu — APPROVED** [review]

**Pull request merged**
