### PR TITLE
platform: Add Corstone-315 (MPS4_CS315) support

### PR DESCRIPTION
**Pull request by david-hazi-arm**
Description
-----------

Test Steps
-----------

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by Skptak — DISMISSED** [review]

**Comment by Skptak** [comment]
Compared the files being added to the listed files from [ARM-software/CMSIS_5](https://github.com/ARM-software/CMSIS_5/tree/a75f01746df18bb5b929dfb8dc6c9407fac3a0f3) at the specified hash and can confirm that these are identical except for whitespace and the comment about their origin.

**Comment by Skptak** [comment]
@david-hazi-arm Can you add the [missing words](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/actions/runs/8562609328/job/23466153503?pr=1130#step:3:1314) to the [.github/.cSpellWords.txt](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/.github/.cSpellWords.txt) file?

I can add it myself if you're okay with me pushing to your branch.

**Comment by david-hazi-arm** [comment]
> @david-hazi-arm Can you add the [missing words](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/actions/runs/8562609328/job/23466153503?pr=1130#step:3:1314) to the [.github/.cSpellWords.txt](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/.github/.cSpellWords.txt) file?
> 
> I can add it myself if you're okay with me pushing to your branch.

Done

**Review by tony-josi-aws — APPROVED** [review]

**Review by Skptak — APPROVED** [review]

**Pull request merged**
