### PR TITLE
Fixes mDNS over IPv6.

### PR DESCRIPTION
**Pull request by evpopov**
I just ran into what appears to be a simple oversight.. maybe someone forgot to copy/paste the mDNS code from v4 to v6
Until this code was added in, my xApplicationDNSQueryHook_Multi() was not getting called at all for IPv6 packets.

Please verify as this was a quick and dirty fix on my end and I may be missing something.

### CODE REVIEW

**Review by htibosch — APPROVED** [review]
It is very wel possible that the code was missing. It has happened in the period when we were all very busy remodeling the IPv6/multi library.
As I'm not in my office these weeks, I can not test it. But I trust that you have tested it well.
Thanks, Hein

**Comment by kstribrnAmzn** [comment]
There looks to be some slight differences between this UDP_IPv6 and [UDP_IPv4 segment](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/dev/IPv6_integration/source/FreeRTOS_UDP_IPv4.c#L529-L548) but I'm no expert here. I'll forward this along to the IPv6 +TCP folks on our team to take a look.

**Comment by kstribrnAmzn** [comment]
@shubnil and @ActoryOu can you take a look?

**Review by ActoryOu — APPROVED** [review]
It looks good to me.

**Review by moninom1 — APPROVED** [review]

**Comment by moninom1** [comment]
Hi @evpopov 

Thank you for the change, we are presently in the process of tagging RC3, we will merge this change after that.
Thank you for the patience.

**Review by moninom1 — APPROVED** [review]

**Review by shubnil — APPROVED** [review]

**Pull request merged**
