### PR TITLE
Split FreeRTOS_TCP_IP.c to 5 files.

### PR DESCRIPTION
**Pull request by xuelix**
Split FreeRTOS_TCP_IP.c to 5 files,
FreeRTOS_TCP_Reception.c
FreeRTOS_TCP_Transmission.c
FreeRTOS_TCP_State_Handling.c
FreeRTOS_TCP_Utils.c

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by AniruddhaKanhere — DISMISSED** [review]

**Comment by AniruddhaKanhere** [comment]
Hello @xuelix,

There are many checks failing. Can you try and fix them?

**Comment by htibosch** [comment]
Hi @xuelix, thank you for this PR. I started checking it by running the compiler.

I found one immediate problem:
~~~c
static const char * prvTCPFlagMeaning( UBaseType_t xFlags );
~~~
The function is declared static in FreeRTOS_TCP_Utils.c, but it is called from FreeRTOS_TCP_IP.c

Now I will run some integration tests.

**Comment by htibosch** [comment]
This chart represents the new division of sources:

image

That is very nice, thank you.

Would you mind to update the \@brief comments that describe the modules, they are unchanged for now:
~~~c
/**
 * @file FreeRTOS_TCP_IP.c
 * @brief Module which handles the TCP connections for FreeRTOS+TCP.
~~~

The tests went well: no problems encountered and the performance is unaffected, as measured with iperf3/TCP: both active and passive transmission.

**Comment by htibosch** [comment]
Xuelix, Aniruddha asked me yesterday about a detail in the function `prvSingleStepTCPHeaderOptions()`.
I think that the followin change is OK:

~~~diff
if( pxSocket->u.xTCP.usMSS > uxNewMSS )
{
    /* our MSS was bigger than the MSS of the other party: adapt it. */
    pxSocket->u.xTCP.bits.bMssChange = pdTRUE_UNSIGNED;

-    if( pxSocket->u.xTCP.usMSS > uxNewMSS )
-    {
        /* The peer advertises a smaller MSS than this socket was
         * using.  Use that as well. */
        FreeRTOS_debug_printf( ( "Change mss %d => %u\n", pxSocket->u.xTCP.usMSS, ( unsigned ) uxNewMSS ) );
-        pxSocket->u.xTCP.usMSS = ( uint16_t ) uxNewMSS;
-    }

    pxTCPWindow->xSize.ulRxWindowLength = ( ( uint32_t ) uxNewMSS ) * ( pxTCPWindow->xSize.ulRxWindowLength / ( ( uint32_t ) uxNewMSS ) );
    pxTCPWindow->usMSSInit = ( uint16_t ) uxNewMSS;
    pxTCPWindow->usMSS = ( uint16_t ) uxNewMSS;
    pxSocket->u.xTCP.usMSS = ( uint16_t ) uxNewMSS;
}
~~~
In older versions of the library the MSS was stored in 2 variables: `usInitMSS` and `usCurMSS`. Later simplified (in [PR 288](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/288/files)) to what it is now.

**Review by htibosch — APPROVED** [review]
Thank you @xuelix for these changes. Now it compiles properly. I approve this PR, although I still have [one remark](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/422#issuecomment-1034505756) about the function `prvSingleStepTCPHeaderOptions()`.

**Review by AniruddhaKanhere — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
